### ISSUE TITLE
Better elements and childs spacing patterns names

### ISSUE THREAD

**Issue by ArmorDarks** [ArmorDarks/ekzo.sass#23]
Find suitable name for patterns

``` scss
.elem+ + .elem+ { margin-top: 10px }

.parent+ {
    .elem + .elem { margin-top: 10px }
}

.parent+ {
    a,
    li
    elem { margin: 10px }
}
```
